### ISSUE TITLE
Karantén konyha?

### ISSUE THREAD

**Issue by qbeer** [dnnagy/myweight#1]
Ez valami, hogy ne hízzunk el karantén alatt repo? :D

**Comment by dnnagy** [comment]
@qbeer Februárban kiderült, hogy gluténérzékeny vagyok, és előtte eléggé le voltam fogyva. Akkor elkezdtem mérni magam, és most hogy diétázok elkezdtem hízni. Azért loggolom a kilókat, hogy lássam, hogy alakul hosszú távon és hogy 24 alatt maradjon a BMI :D

**Comment by qbeer** [comment]
Azta, hát akkor hajrá hozzá.
